[package]
name = "postui-core"
edition.workspace = true
version.workspace = true

[dependencies]
serde.workspace = true
indexmap.workspace = true
thiserror.workspace = true
serde_json = { workspace = true, features = ["preserve_order", "arbitrary_precision"] }
toml.workspace = true
toml_edit.workspace = true
tempfile.workspace = true
directories.workspace = true
form_urlencoded.workspace = true
