[package]
name = "postui"
edition.workspace = true
version.workspace = true

[dependencies]
postui-core = { path = "../postui-core" }
anyhow.workspace = true
serde.workspace = true
toml.workspace = true
ratatui = "0.30"
crossterm = { version = "0.29", features = ["event-stream"] }
tokio = { version = "1", features = ["rt-multi-thread", "macros", "sync", "time"] }
futures = "0.3"
directories = "6"

[dev-dependencies]
